name: Tag New Version and Release

on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: George-Ogden/actions/.github/workflows/python-release.yaml@v3.1.1
    with:
      validation-code: "import module; check import"
