name: Test

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:
  test:
    uses: George-Ogden/actions/.github/workflows/python-test.yaml@v3.1.2
    with:
      python-versions: "['3.11', '3.12', '3.13']"
